input_path =
  case System.argv() do
    [path] -> path
    _ -> raise "usage: elixir dev/generate_html_entity_data.exs /path/to/entities.json"
  end

json = File.read!(input_path)

entities =
  json
  |> :json.decode()
  |> Enum.map(fn {<<"&", name::binary>>, %{"characters" => characters}} ->
    {name, characters}
  end)
  |> Enum.sort()

entries =
  Enum.map_join(entities, ",\n", fn {name, characters} ->
    "    #{inspect(name)} => #{inspect(characters, printable_limit: :infinity)}"
  end)

max_name_length =
  entities
  |> Enum.map(fn {name, _characters} -> byte_size(name) end)
  |> Enum.max()

checksum =
  :sha256
  |> :crypto.hash(json)
  |> Base.encode16(case: :lower)

source = """
# Generated from https://html.spec.whatwg.org/entities.json.
# Retrieved #{Date.utc_today()}; SHA-256 #{checksum}.
# Do not edit this file manually. Regenerate it with dev/generate_html_entity_data.exs.
# The source data is used under the WHATWG BSD 3-Clause License. Its copyright
# and license terms are retained in priv/licenses/WHATWG-BSD-3-Clause.txt.

defmodule NativeElixirPdfUtilities.HtmlToPdf.HtmlEntityData do
  @moduledoc false

  @entities %{
#{entries}
  }

  @doc false
  @spec lookup(String.t()) :: String.t() | nil
  def lookup(name) do
    Map.get(@entities, name)
  end

  @doc false
  @spec max_name_length() :: pos_integer()
  def max_name_length do
    #{max_name_length}
  end

  @doc false
  @spec entity_count() :: pos_integer()
  def entity_count do
    #{length(entities)}
  end
end
"""

File.write!("lib/html_to_pdf/html_entity_data.ex", source)
