ARG BASE_IMAGE=sigdevelopers/sigportal-ci:v2.6
FROM ${BASE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      chromium \
      fonts-dejavu-core \
      fonts-liberation \
      poppler-utils \
    && rm -rf /var/lib/apt/lists/*
